FROM percona:5.6

RUN apt-get update && apt-get -y install wget && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN echo aap
# COPY database/* /docker-entrypoint-initdb.d/

EXPOSE 3306
CMD ["mysqld"]
